version: '3'

services:
  db:
    container_name: postgres_code_challenge
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: code_challenge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      timeout: 20s
      retries: 10
    ports:
      - '5432:5432'
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/app", "migrate" ]
    depends_on:
      db:
        condition: service_healthy
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    entrypoint: [ "/app", "serve" ]
#    ports:
#      - "8080:8080"
#    depends_on:
#      migrate:
#        condition: service_completed_successfully
