version: '3'

services:
  db:
    container_name: postgres_code_challenge
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: code_challenge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      timeout: 20s
      retries: 10
    ports:
      - '5432:5432'
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/app", "migrate" ]
    depends_on:
      db:
        condition: service_healthy
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4566:4566" # Edge port for all services
      - "4572:4572" # S3 service port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/app", "serve" ]
    ports:
      - "4000:4000"
    depends_on:
      migrate:
        condition: service_completed_successfully